version: "3"
services:
  python3:
    build: .
    container_name: "python3"
    restart: unless-stopped
    working_dir: "/work"
    env_file:
      - .env
    tty: true
    volumes:
      - ./work:/work

  my_postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
