services:
  python3:
    build: ./work
    container_name: "python3"
    restart: unless-stopped
    working_dir: "/work"
    env_file:
      - .env
    tty: true
    volumes:
      - ./work:/work
      - ./db:/db
    depends_on:
      my_postgres:
        condition: service_healthy

  fastapi_app:
    build: ./fastapi_app
    container_name: "fastapi_app"
    restart: unless-stopped
    working_dir: "/fastapi_app"
    env_file:
      - .env
    tty: true
    volumes:
      - ./fastapi_app:/fastapi_app
      - ./db:/db
    ports:
      - "8000:8000"
    depends_on:
      my_postgres:
        condition: service_healthy
  redis:
    image: redis:6.2  # Redis の公式イメージ
    ports:
      - "6379:6379"  # Redis の公開ポート
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  my_postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d weather"]
      interval: 10s      # ヘルスチェック間隔
      timeout: 5s        # タイムアウト
      retries: 5         # リトライ回数
      start_period: 30s 

volumes:
  postgres_data:
  redis-data:
